apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: k-s-demo-app
build:
  artifacts:
  - image: ccr.ccs.tencentyun.com/kioyong/k8s-demo-app
    jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
